#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        servlet:
#          DispatcherServlet: DEBUG
#        web: INFO
#    br:
#      com:
#        lsena:
#          sportsfree: DEBUG
#spring:
#  application:
#    name: sportsfree
#  datasource:
#    username: sa
#    password:
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    hibernate:
#      ddl-auto: update
#      show-sql: true

