keycloak:
  realm: SportsFree
  auth-server-url: http://localhost:8181/auth
  ssl-required: external
  resource: sportsfree-backend
  credentials:
    secret: 7b599604-d276-4bf6-b65d-fd49a8e0447d
#  public-client: true
#  principal-attribute: preferred_username
  use-resource-role-mappings: true
#  bearer-only: true
#  security-constraints:
#    - authRoles:
#        - user
#        - admin
#    - securityCollections:
#        -
#        - patterns:
#            - /professor/**
